name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'Trung'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
    default: ${{ github.token }}
  REPOSITORY:
    description: 'The repository where the action will be executed'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code'
    required: true
  LABEL:
    description: 'The label assigned to GitHub issues that should be processed by the AutoCoder action. Only issues with this label will trigger the code generation process.'
    required: true
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'
  steps:
    - name: Setup permissions for script
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Run Script
      run: ${{ inputs.SCRIPT_PATH }} ${{ inputs.GITHUB_TOKEN }} ${{ inputs.REPOSITORY }} ${{ inputs.ISSUE_NUMBER }} ${{ inputs.OPENAI_API_KEY }}
      shell: bash

    - name: Commit changes
      run: |
        git config --global user.name 'autocoder-bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Auto coder changes"
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        base: 'main'
        body: |
          This PR was created automatically by Auto Coder.
          It includes:
          - Changes generated by the script.
        labels: ${{ inputs.LABEL }}
        commit-message: 'Auto coder changes'
        delete-branch: false
