name: Auto coder
on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    environment: Auto Coder
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup permissions for script
          run: |
            ls -Rl .
            chmod +x ./scripts/script.sh

        - name: Run Script
          env:
            CHAT_GPT_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
          run: |
            echo ${{ secrets.GITHUB_TOKEN }}
            echo ${{ github.repository }}
            echo ${{ github.event.issue.number }}
            echo ${{ env.CHAT_GPT_API_KEY }}
            ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.issue.number }} ${{ env.CHAT_GPT_API_KEY }}

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: autocoder-artifact
            path: |
              ./* 
              !./.github/**
              !./.git/** 
              !./*.yml

        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: autocoder-artifact
            path: ./autocoder-artifact

        - name: Display files in artifact
          run: ls -Rl ./autocoder-artifact