name: Auto coder
on:
  issues:
    types: [ opened, reopened, labeled ]
permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    environment: Auto Coder
    env:
      AUTO_CODER_BRANCH: autocoder-branch-${{ github.event.issue.number }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create and switch to branch
        run: |
          git checkout -b $AUTO_CODER_BRANCH || git checkout $AUTO_CODER_BRANCH

      - name: Setup permissions for script
        run: chmod +x ./scripts/script.sh

      - name: Run Script
        env:
          CHAT_GPT_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
        run: ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.issue.number }} ${{ env.CHAT_GPT_API_KEY }}

      - name: Create Branch if Not Exist
        run: |
          git fetch origin
          if git rev-parse --verify origin/${{env.AUTO_CODER_BRANCH}}; then
            git checkout ${{env.AUTO_CODER_BRANCH}}
          else
            git checkout -b ${{env.AUTO_CODER_BRANCH}} origin/main
            git push origin ${{env.AUTO_CODER_BRANCH}}
          fi

      - name: Commit changes
        run: |
          git config --global user.name 'autocoder-bot'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Auto coder changes"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ env.AUTO_CODER_BRANCH }}
          base: 'main'
          title: 'Auto Coder Pull Request'
          body: |
            This PR was created automatically by Auto Coder.
            It includes the following changes:
            - Automated changes from the script.
          labels: 'autocoder-bot'
          commit-message: "Update PR with new changes"
          delete-branch: true
