name: Auto coder
on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup permissions for script
          run: |
            chmod +x ./scripts/script.sh

        - name: Run Script
          run: ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.issue.number }} ${{ secrets.CHAT_GPT_API_KEY }}

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: autocoder-artifact
            path: |
              ./* 
              !./.github/**
              !./.git/** 
              !./*.yml

        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: autocoder-artifact
            path: ./autocoder-artifact

        - name: Display files in artifact
          run: ls -l ./autocoder-artifact