name: Auto coder
on:
  issues:
    types: [opened, reopened, labeled]
permissions:
  contents: write
  pull-requests: write

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    environment: Auto Coder
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup permissions for script
          run: chmod +x ./scripts/script.sh

        - name: Run Script
          env:
            CHAT_GPT_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
          run: ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.issue.number }} ${{ env.CHAT_GPT_API_KEY }}

        - name: Commit and push changes
          run: |
            git config --global user.name 'autocoder-bot'
            git config --global user.email 'actions@github.com'
            git add .
            git commit -m "Auto coder changes"
            git push

        - name: Create a Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
            branch: 'autocoder-branch-${{ github.event.issue.number }}'
            base: 'main'
            labels: 'autocoder-bot'
