name: Auto coder
on:
  issues:
    types: [opened, reopened, labeled]
permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    environment: Auto Coder
    env:
      AUTO_CODER_BRANCH: autocoder-branch-${{ github.event.issue.number }}
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup permissions for script
          run: chmod +x ./scripts/script.sh

        - name: Run Script
          env:
            CHAT_GPT_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
          run: ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.issue.number }} ${{ env.CHAT_GPT_API_KEY }}

        - name: Check if branch exists
          run: |
            git ls-remote --exit-code --heads origin $AUTO_CODER_BRANCH || git checkout -b $AUTO_CODER_BRANCH

        - name: Pull changes from remote (if exists)
          run: |
            git pull origin $AUTO_CODER_BRANCH --rebase || true

        - name: Commit changes
          run: |
            git config --global user.name 'autocoder-bot'
            git config --global user.email 'actions@github.com'
            git add .
            git diff-index --quiet HEAD || git commit -m "Auto coder changes"

        - name: Push changes
          run: |
            git push origin $AUTO_CODER_BRANCH --force

        - name: Create a Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
            branch: ${{ env.AUTO_CODER_BRANCH }}
            base: 'main'
            labels: 'autocoder-bot'
