name: Auto coder
on:
  issues:
    types: [opened, reopened, labeled]
permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    environment: Auto Coder
    env:
      AUTO_CODER_BRANCH: autocoder-branch-${{ github.event.issue.number }}
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Create and switch to branch
          run: |
            git checkout -b $AUTO_CODER_BRANCH || git checkout $AUTO_CODER_BRANCH

        - name: Setup permissions for script
          run: chmod +x ./scripts/script.sh

        - name: Run Script
          env:
            CHAT_GPT_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
          run: ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.issue.number }} ${{ env.CHAT_GPT_API_KEY }}

        - name: Commit changes
          run: |
            git config --global user.name 'autocoder-bot'
            git config --global user.email 'actions@github.com'
            git add .
            git commit -m "Auto coder changes"

        - name: Push changes
          run: |
            git push origin $AUTO_CODER_BRANCH

        - name: Create Pull Request via API
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls \
              -d '{
                "title": "Auto Coder Pull Request",
                "head": "'"$AUTO_CODER_BRANCH"'",
                "base": "main",
                "body": "This PR was created automatically by Auto Coder.",
                "labels": ["autocoder-bot"]
              }'
