name: Auto coder
on:
  issue:
    types: [created, reopened]

jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout

        - name: Print Issue Information
          env:
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            ISSUE_BODY: ${{ github.event.issue.body }}
            ISSUE_ASSIGNEES:  ${{ join(github.event.issue.assignees.*.login, ', ') }}
            ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
            ISSUE_RESPONSE: $(curl -s https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER)
          run: |
            echo "Issue Number: ${ISSUE_NUMBER}"
            echo "Issue Body: ${ISSUE_BODY}"
            echo "Issue Assignees: ${ISSUE_ASSIGNEES}"
            echo "Issue Labels: ${ISSUE_LABELS}"
            echo "Issue Response: ${ISSUE_RESPONSE}"
