name: Auto coder
on:
  issues:
    types: [ opened, reopened, labeled ]
permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    environment: Auto Coder
    env:
      AUTO_CODER_BRANCH: autocoder-branch-${{ github.event.issue.number }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AutoCoder Composite Action
        uses: trung-cly/AutoCoder@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
          SCRIPT_PATH: './scripts/script.sh'
          LABEL: 'autocoder-bot'
